/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.dotspots.rpcplus.example.torturetest;


import java.util.Set;
import java.util.HashSet;
import java.util.Collections;
import org.apache.thrift.IntRangeSet;

public class SimpleEnum {
  public static final int ONE = 1;
  public static final int TWO = 2;

  public static final IntRangeSet VALID_VALUES = new IntRangeSet(ONE, TWO);
}
