/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.dotspots.rpcplus.example.torturetest;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;
import java.util.HashSet;
import java.util.Collections;
import org.apache.thrift.*;
import org.apache.thrift.meta_data.*;

import org.apache.thrift.protocol.*;
import org.apache.thrift.transport.*;

public class ObjectWithEnum implements TBase, java.io.Serializable, Cloneable {
  private static final TStruct STRUCT_DESC = new TStruct("ObjectWithEnum");
  private static final TField ENUM_VALUE_FIELD_DESC = new TField("enumValue", TType.I32, (short)1);

  private int enumValue;
  public static final int ENUMVALUE = 1;

  private final Isset __isset = new Isset();
  private static final class Isset implements java.io.Serializable {
    public boolean enumValue = false;
  }

  public static final Map<Integer, FieldMetaData> metaDataMap = Collections.unmodifiableMap(new HashMap<Integer, FieldMetaData>() {{
    put(ENUMVALUE, new FieldMetaData("enumValue", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.I32)));
  }});

  static {
    FieldMetaData.addStructMetaDataMap(ObjectWithEnum.class, metaDataMap);
  }

  public ObjectWithEnum() {
  }

  public ObjectWithEnum(
    int enumValue)
  {
    this();
    this.enumValue = enumValue;
    this.__isset.enumValue = true;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ObjectWithEnum(ObjectWithEnum other) {
    __isset.enumValue = other.__isset.enumValue;
    this.enumValue = other.enumValue;
  }

  @Override
  public ObjectWithEnum clone() {
    return new ObjectWithEnum(this);
  }

  public int getEnumValue() {
    return this.enumValue;
  }

  public void setEnumValue(int enumValue) {
    this.enumValue = enumValue;
    this.__isset.enumValue = true;
  }

  public void unsetEnumValue() {
    this.__isset.enumValue = false;
  }

  // Returns true if field enumValue is set (has been asigned a value) and false otherwise
  public boolean isSetEnumValue() {
    return this.__isset.enumValue;
  }

  public void setFieldValue(int fieldID, Object value) {
    switch (fieldID) {
    case ENUMVALUE:
      if (value == null) {
        unsetEnumValue();
      } else {
        setEnumValue((Integer)value);
      }
      break;

    default:
      throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
    }
  }

  public Object getFieldValue(int fieldID) {
    switch (fieldID) {
    case ENUMVALUE:
      return getEnumValue();

    default:
      throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
    }
  }

  // Returns true if field corresponding to fieldID is set (has been asigned a value) and false otherwise
  public boolean isSet(int fieldID) {
    switch (fieldID) {
    case ENUMVALUE:
      return isSetEnumValue();
    default:
      throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
    }
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ObjectWithEnum)
      return this.equals((ObjectWithEnum)that);
    return false;
  }

  public boolean equals(ObjectWithEnum that) {
    if (that == null)
      return false;

    boolean this_present_enumValue = true;
    boolean that_present_enumValue = true;
    if (this_present_enumValue || that_present_enumValue) {
      if (!(this_present_enumValue && that_present_enumValue))
        return false;
      if (this.enumValue != that.enumValue)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) { 
        break;
      }
      switch (field.id)
      {
        case ENUMVALUE:
          if (field.type == TType.I32) {
            this.enumValue = iprot.readI32();
            this.__isset.enumValue = true;
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
          break;
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    validate();
  }

  public void write(TProtocol oprot) throws TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    oprot.writeFieldBegin(ENUM_VALUE_FIELD_DESC);
    oprot.writeI32(this.enumValue);
    oprot.writeFieldEnd();
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ObjectWithEnum(");
    boolean first = true;

    sb.append("enumValue:");
    sb.append(this.enumValue);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    // check that fields of type enum have valid values
    if (__isset.enumValue && !SimpleEnum.VALID_VALUES.contains(enumValue)){
      throw new TProtocolException("Invalid value of field 'enumValue'!");
    }
  }

}

