/* Generated By:JJTree: Do not edit this line. DynamicSerDeFunctionType.java */

package org.apache.hadoop.hive.serde2.dynamic_type;

public class DynamicSerDeFunctionType extends SimpleNode {
	protected DynamicSerDeFieldType type;

	public DynamicSerDeFunctionType(int id) {
		super(id);
	}

	public DynamicSerDeFunctionType(thrift_grammar p, int id) {
		super(p, id);
	}

	@Override
	public String toString() {
		return type == null ? "void" : type.getMyType().toString();
	}

	public DynamicSerDeFieldType getType() {
		return type;
	}
}
