/* Generated By:JJTree: Do not edit this line. DynamicSerDeXception.java */

package org.apache.hadoop.hive.serde2.dynamic_type;

import org.apache.thrift.protocol.TType;

public class DynamicSerDeXception extends DynamicSerDeStructBase {
	final private static int FD_FIELD_LIST = 0;

	public DynamicSerDeXception(int id) {
		super(id);
	}

	public DynamicSerDeXception(thrift_grammar p, int id) {
		super(p, id);
	}

	@Override
	public String toString() {
		String result = "exception " + this.namespace + "." + this.name + "(";
		result += this.getFieldList().toString();
		result += ")";
		return result;
	}

	@Override
	public DynamicSerDeFieldList getFieldList() {
		return (DynamicSerDeFieldList) this.jjtGetChild(FD_FIELD_LIST);
	}

	@Override
	public byte getType() {
		return TType.STRUCT;
	}

}
