/* Generated By:JJTree: Do not edit this line. DynamicSerDeService.java */

package org.apache.hadoop.hive.serde2.dynamic_type;

import java.util.ArrayList;
import java.util.List;

public class DynamicSerDeService extends SimpleNode {
	protected String name;
	protected String namespace;

	public DynamicSerDeService(int id) {
		super(id);
	}

	public DynamicSerDeService(thrift_grammar p, int id) {
		super(p, id);
	}

	public String getName() {
		return name;
	}

	public List<DynamicSerDeFunction> getFunctions() {
		List<DynamicSerDeFunction> functions = new ArrayList<DynamicSerDeFunction>();
		for (int i = 0; i < this.jjtGetNumChildren(); i++) {
			if (jjtGetChild(i) instanceof DynamicSerDeFunction) {
				functions.add((DynamicSerDeFunction) jjtGetChild(i));
			}
		}

		return functions;
	}

	@Override
	public String toString() {
		String result = "service " + namespace + "." + name + "{\n";
		for (DynamicSerDeFunction func : getFunctions()) {
			result += "    " + func.toString() + "\n";
		}
		result += "}\n";
		return result;
	}

	public String getNamespace() {
		return namespace;
	}
}
