// AUTOGENERATED: See com.dotspots.rpcplus.codegen.jscollections.CollectionGen for more details
package com.dotspots.rpcplus.client.jscollections;

import com.google.gwt.core.client.JavaScriptObject;
import com.google.gwt.core.client.GWT;
import com.google.gwt.lang.LongLib;

@SuppressWarnings("unused")
public final class JsRpcListDouble extends JavaScriptObject {
    protected JsRpcListDouble() {
    }

    public static JsRpcListDouble create() {
        return JavaScriptObject.createArray().cast();
    }

    public native boolean contains(int idx) /*-{
        return (idx in this);
    }-*/;

    public native int size() /*-{
        return this.length;
    }-*/;

    public native boolean isEmpty() /*-{
        return !this.length;
    }-*/;

    public native void remove(int idx) /*-{
        this.splice(idx, 1);
    }-*/;

    public native boolean forEach(JsRpcDoubleProcedure procedure) /*-{
        for (var i = 0; i < this.length; i++) { 
            if (!procedure.@com.dotspots.rpcplus.client.jscollections.JsRpcDoubleProcedure::execute(D)(this[i])) return false;
        }
        return true;
    }-*/;

    public native boolean forEach(JsRpcIntDoubleProcedure procedure) /*-{
        for (var i = 0; i < this.length; i++) { 
            if (!procedure.@com.dotspots.rpcplus.client.jscollections.JsRpcIntDoubleProcedure::execute(ID)(i, this[i])) return false;
        }
        return true;
    }-*/;

    public native double get(int idx) /*-{
        return this[idx] || 0;
    }-*/;

    public native void set(int idx, double value) /*-{
        this[idx] = value;
    }-*/;

    public native void add(double value) /*-{
        this.push(value);
    }-*/;

    public native void pop() /*-{
        this.pop();
    }-*/;

    public double peek() {
        return this.get(this.size() - 1);
    };

    public native String join(String separator) /*-{
        return this.join(separator);
    }-*/;

    public native JsRpcListDouble slice(int index) /*-{
        return this.slice(index);
    }-*/;

    public native JsRpcListDouble slice(int from, int to) /*-{
        return this.slice(from, to);
    }-*/;

    public native JsRpcListDouble clear() /*-{
        this.splice(0, this.length);
    }-*/;

    public native JsRpcListDouble splice(int index) /*-{
        return this.splice(index, this.length);
    }-*/;

    public native JsRpcListDouble splice(int index, int howMany) /*-{
        return this.splice(index, howMany);
    }-*/;

}
