// AUTOGENERATED: See com.dotspots.rpcplus.codegen.jscollections.CollectionGen for more details
package com.dotspots.rpcplus.client.jscollections;

import com.google.gwt.core.client.JavaScriptObject;
import com.google.gwt.core.client.UnsafeNativeLong;
import com.google.gwt.core.client.GWT;
import com.google.gwt.lang.LongLib;

@SuppressWarnings("unused")
public final class JsRpcListLong extends JavaScriptObject {
    protected JsRpcListLong() {
    }

    public static JsRpcListLong create() {
        return JavaScriptObject.createArray().cast();
    }

    public native boolean contains(int idx) /*-{
        return this.hasOwnProperty(idx);
    }-*/;

    public native int size() /*-{
        return this.length;
    }-*/;

    public native boolean isEmpty() /*-{
        return !this.length;
    }-*/;

    public native void remove(int idx) /*-{
        this.splice(idx, 1);
    }-*/;

    @UnsafeNativeLong
    public native long get(int idx) /*-{
        return @com.dotspots.rpcplus.client.jscollections.RpcUtils::fromDoubles(Lcom/google/gwt/core/client/JavaScriptObject;)(this[idx] || [0,0]);
    }-*/;

    @UnsafeNativeLong
    public native void set(int idx, long value) /*-{
        this[idx] = @com.dotspots.rpcplus.client.jscollections.RpcUtils::toDoubles(J)(value);
    }-*/;

    /**
     * Adds an item to the end of the list, returning the list's new size.
     */
    @UnsafeNativeLong
    public native int add(long value) /*-{
        return this.push(@com.dotspots.rpcplus.client.jscollections.RpcUtils::toDoubles(J)(value));
    }-*/;

    /**
     * Adds an item to the end of the list, returning the list's new size.
     */
    @UnsafeNativeLong
    public native int push(long value) /*-{
        return this.push(@com.dotspots.rpcplus.client.jscollections.RpcUtils::toDoubles(J)(value));
    }-*/;

    /**
     * Pops an item off the end of the list, returning it.
     */
    @UnsafeNativeLong
    public native long pop() /*-{
        return @com.dotspots.rpcplus.client.jscollections.RpcUtils::fromDoubles(Lcom/google/gwt/core/client/JavaScriptObject;)(this.pop() || [0,0]);
    }-*/;

    /**
     * Peeks at the item at the end of the list.
     */
    public long peek() {
        return this.get(this.size() - 1);
    };

    /**
     * Unshifts an item into position 0, returning the new size of the list.
     */
    @UnsafeNativeLong
    public native int unshift(long value) /*-{
        return this.unshift(@com.dotspots.rpcplus.client.jscollections.RpcUtils::toDoubles(J)(value));
    }-*/;

    /**
     * Shifts an item out of position 0 and returns it.
     */
    @UnsafeNativeLong
    public native long shift() /*-{
        return @com.dotspots.rpcplus.client.jscollections.RpcUtils::fromDoubles(Lcom/google/gwt/core/client/JavaScriptObject;)(this.shift() || [0,0]);
    }-*/;

    public native String join(String separator) /*-{
        return this.join(separator);
    }-*/;

    public native JsRpcListLong slice(int index) /*-{
        return this.slice(index);
    }-*/;

    public native JsRpcListLong slice(int from, int to) /*-{
        return this.slice(from, to);
    }-*/;

    public native JsRpcListLong clear() /*-{
        this.splice(0, this.length);
    }-*/;

    public native JsRpcListLong splice(int index) /*-{
        return this.splice(index, this.length);
    }-*/;

    public native JsRpcListLong splice(int index, int howMany) /*-{
        return this.splice(index, howMany);
    }-*/;

}
