// AUTOGENERATED: See com.dotspots.rpcplus.codegen.jscollections.CollectionGen for more details
package com.dotspots.rpcplus.client.jscollections;

import com.google.gwt.core.client.JavaScriptObject;
import com.google.gwt.core.client.UnsafeNativeLong;
import com.google.gwt.core.client.GWT;
import com.google.gwt.lang.LongLib;

@SuppressWarnings("unused")
public final class JsRpcMapStringLong extends JavaScriptObject {
    protected JsRpcMapStringLong() {
    }

    public static JsRpcMapStringLong create() {
        return JavaScriptObject.createObject().cast();
    }

    public native boolean contains(String idx) /*-{
        return this.hasOwnProperty('_' + idx);
    }-*/;

    /**
     * Counts the size of a collection through brute force (slow).
     */
    public native int countSize() /*-{
        var l = 0; for (x in this) if (this.hasOwnProperty(x)) l++; return l;
    }-*/;

    public native boolean isEmpty() /*-{
        for (x in this) if (this.hasOwnProperty(x)) return false; return true;
    }-*/;

    public native void remove(String idx) /*-{
        delete this['_' + idx];
    }-*/;

    @UnsafeNativeLong
    public native long get(String idx) /*-{
        return @com.dotspots.rpcplus.client.jscollections.RpcUtils::fromDoubles(Lcom/google/gwt/core/client/JavaScriptObject;)(this['_' + idx] || [0,0]);
    }-*/;

    @UnsafeNativeLong
    public native void set(String idx, long value) /*-{
        this['_' + idx] = @com.dotspots.rpcplus.client.jscollections.RpcUtils::toDoubles(J)(value);
    }-*/;

}
