// AUTOGENERATED: See com.dotspots.thrift.gwt.codegen.collections.CollectionGen for more details
package com.dotspots.rpcplus.client.jscollections;

import com.google.gwt.core.client.JavaScriptObject;
import com.google.gwt.core.client.GWT;
import com.google.gwt.lang.LongLib;

@SuppressWarnings("unused")
public final class JsRpcListInt extends JavaScriptObject {
    protected JsRpcListInt() {
    }

    public static JsRpcListInt create() {
        return JavaScriptObject.createArray().cast();
    }

    public native boolean contains(int idx) /*-{
        return (idx in this);
    }-*/;

    public native int size() /*-{
        return this.length;
    }-*/;

    public native boolean isEmpty() /*-{
        return !this.length;
    }-*/;

    public native void remove(int idx) /*-{
        this.splice(idx, 1);
    }-*/;

    public native int get(int idx) /*-{
        return this[idx] || 0;
    }-*/;

    public native void set(int idx, int value) /*-{
        this[idx] = value;
    }-*/;

    public native void add(int value) /*-{
        this.push(value);
    }-*/;

}
