// AUTOGENERATED: See com.dotspots.rpcplus.codegen.jscollections.CollectionGen for more details
package com.dotspots.rpcplus.client.jscollections;

import com.google.gwt.core.client.JavaScriptObject;
import com.google.gwt.core.client.UnsafeNativeLong;
import com.google.gwt.core.client.GWT;
import com.google.gwt.lang.LongLib;

@SuppressWarnings("unused")
public final class JsRpcList<E> extends JavaScriptObject {
    protected JsRpcList() {
    }

    public static <E> JsRpcList<E> create() {
        return JavaScriptObject.createArray().cast();
    }

    public native boolean contains(int idx) /*-{
        return this.hasOwnProperty(idx);
    }-*/;

    public native int size() /*-{
        return this.length;
    }-*/;

    public native boolean isEmpty() /*-{
        return !this.length;
    }-*/;

    public native void remove(int idx) /*-{
        this.splice(idx, 1);
    }-*/;

    public boolean forEach(JsRpcObjectProcedure<E> procedure) {
        for (int i = 0; i < size(); i++) { 
            if (!procedure.execute(get(i))) return false;
        }
        return true;
    };

    public boolean forEach(JsRpcIntObjectProcedure<E> procedure) {
        for (int i = 0; i < size(); i++) { 
            if (!procedure.execute(i, get(i))) return false;
        }
        return true;
    };

    @UnsafeNativeLong
    public native E get(int idx) /*-{
        return this[idx] || null;
    }-*/;

    @UnsafeNativeLong
    public native void set(int idx, E value) /*-{
        this[idx] = value;
    }-*/;

    /**
     * Adds an item to the end of the list, returning the list's new size.
     */
    @UnsafeNativeLong
    public native int add(E value) /*-{
        return this.push(value);
    }-*/;

    /**
     * Adds an item to the end of the list, returning the list's new size.
     */
    @UnsafeNativeLong
    public native int push(E value) /*-{
        return this.push(value);
    }-*/;

    /**
     * Pops an item off the end of the list, returning it.
     */
    @UnsafeNativeLong
    public native E pop() /*-{
        return this.pop() || null;
    }-*/;

    /**
     * Peeks at the item at the end of the list.
     */
    public E peek() {
        return this.get(this.size() - 1);
    };

    /**
     * Unshifts an item into position 0, returning the new size of the list.
     */
    @UnsafeNativeLong
    public native int unshift(E value) /*-{
        return this.unshift(value);
    }-*/;

    /**
     * Shifts an item out of position 0 and returns it.
     */
    @UnsafeNativeLong
    public native E shift() /*-{
        return this.shift() || null;
    }-*/;

    public native String join(String separator) /*-{
        return this.join(separator);
    }-*/;

    public native JsRpcList<E> slice(int index) /*-{
        return this.slice(index);
    }-*/;

    public native JsRpcList<E> slice(int from, int to) /*-{
        return this.slice(from, to);
    }-*/;

    public native JsRpcList<E> clear() /*-{
        this.splice(0, this.length);
    }-*/;

    public native JsRpcList<E> splice(int index) /*-{
        return this.splice(index, this.length);
    }-*/;

    public native JsRpcList<E> splice(int index, int howMany) /*-{
        return this.splice(index, howMany);
    }-*/;

}
