/* Generated By:JJTree: Do not edit this line. DynamicSerDeEnumDefList.java */

package org.apache.hadoop.hive.serde2.dynamic_type;

public class DynamicSerDeEnumDefList extends SimpleNode {
	public DynamicSerDeEnumDefList(int id) {
		super(id);
	}

	public DynamicSerDeEnumDefList(thrift_grammar p, int id) {
		super(p, id);
	}

	final public DynamicSerDeEnumDef[] getChildren() {
		int size = this.jjtGetNumChildren();
		DynamicSerDeEnumDef result[] = new DynamicSerDeEnumDef[size];
		for (int i = 0; i < size; i++) {
			result[i] = (DynamicSerDeEnumDef) this.jjtGetChild(i);
		}
		return result;
	}

	@Override
	public String toString() {
		StringBuffer result = new StringBuffer();
		String prefix = "";
		for (DynamicSerDeEnumDef t : this.getChildren()) {
			result.append(prefix + t.getName() + " = " + t.getValue());
			prefix = ", ";
		}
		return result.toString();
	}

}
