/* Generated By:JJTree: Do not edit this line. DynamicSerDeEnumDef.java */

package org.apache.hadoop.hive.serde2.dynamic_type;

public class DynamicSerDeEnumDef extends SimpleNode {
	protected String name;
	protected String value;

	public DynamicSerDeEnumDef(int id) {
		super(id);
	}

	public DynamicSerDeEnumDef(thrift_grammar p, int id) {
		super(p, id);
	}

	public String getName() {
		return name;
	}

	public int getValue() {
		return Integer.valueOf(value);
	}

}
