/* Generated By:JJTree: Do not edit this line. DynamicSerDeEnum.java */

package org.apache.hadoop.hive.serde2.dynamic_type;

public class DynamicSerDeEnum extends DynamicSerDeTypeBase {
	final private static int FD_FIELD_LIST = 0;

	public DynamicSerDeEnum(int id) {
		super(id);
	}

	public DynamicSerDeEnum(thrift_grammar p, int id) {
		super(p, id);
	}

	@Override
	public String toString() {
		return "enum " + namespace + "." + name + "{" + getFieldList() + "}";
	}

	public DynamicSerDeEnumDefList getFieldList() {
		return (DynamicSerDeEnumDefList) this.jjtGetChild(FD_FIELD_LIST);
	}
}
